In [15]:
import pandas as pd
df = pd.read_csv ('featurelistcsv2.csv')
print(df)

ModuleNotFoundError: No module named 'pandas'

In [68]:
dfdash=pd.read_csv('lacguDcalcCopy.csv')
print(dfdash)

      Logdist_LNCacguD  Logdist_PCTacguD  Logdist_acguD         MFE   Up_Freq
0            -1.151985         -1.154264       0.998026 -240.699997  0.129213
1            -1.108212         -1.101415       1.006171 -195.500000  0.099065
2            -1.242530         -1.243256       0.999417 -403.600006  0.112890
3            -1.116135         -1.117372       0.998893 -214.899994  0.106780
4            -1.536138         -1.528239       1.005169 -850.099976  0.109898
...                ...               ...            ...         ...       ...
8133         -1.749523         -1.791755       0.976430 -174.100006  0.128205
8134         -1.990256         -2.041748       0.974781  -95.699997  0.126521
8135         -1.087554         -1.091028       0.996816 -163.699997  0.120200
8136         -1.106690         -1.099381       1.006649 -179.699997  0.120069
8137         -1.087352         -1.089796       0.997758 -801.700012  0.119667

[8138 rows x 5 columns]


In [69]:
dfdash1=dfdash.dropna()
dfdash1

Logdist_LNCacguD  Logdist_PCTacguD  Logdist_acguD         MFE   Up_Freq
0            -1.151985         -1.154264       0.998026 -240.699997  0.129213
1            -1.108212         -1.101415       1.006171 -195.500000  0.099065
2            -1.242530         -1.243256       0.999417 -403.600006  0.112890
3            -1.116135         -1.117372       0.998893 -214.899994  0.106780
4            -1.536138         -1.528239       1.005169 -850.099976  0.109898
...                ...               ...            ...         ...       ...
8133         -1.749523         -1.791755       0.976430 -174.100006  0.128205
8134         -1.990256         -2.041748       0.974781  -95.699997  0.126521
8135         -1.087554         -1.091028       0.996816 -163.699997  0.120200
8136         -1.106690         -1.099381       1.006649 -179.699997  0.120069
8137         -1.087352         -1.089796       0.997758 -801.700012  0.119667

[8138 rows x 5 columns]

In [58]:
import pickle
with open('zerolistlnc.pkl', 'rb') as f:
    zerolist = pickle.load(f)

In [59]:
zerolist

[91, 571, 659, 902, 1161, 2610]

In [66]:
dfdash1.drop(df.index[[91, 571, 659, 902, 1161, 2610]],axis=0,inplace=True)


In [70]:
import pandas as pd
dfnew=pd.concat([df, dfdash1], axis=1)
dfnew

Unnamed: 0  orf_length  orf_coverage  Logdist_LNCORF  Logdist_PCTORF  \
0              0         228      0.320225       -1.047841       -1.053617   
1              1         111      0.207477       -1.019344       -1.020377   
2              2         258      0.217355       -1.061407       -1.059868   
3              3         225      0.381356       -1.052068       -1.050217   
4              4         240      0.087336       -1.057371       -1.057873   
...          ...         ...           ...             ...             ...   
8133        8133         618      0.880342       -1.174580       -1.168850   
8134        8134          66      0.160584       -1.008640       -1.007566   
8135        8135          36      0.060100       -1.002576       -1.003204   
8136        8136         291      0.499142       -1.072277       -1.071994   
8137        8137        1779      0.617066       -1.562632       -1.563355   

      Logdist_ORF       Q1      Q2  max_value  min_value       snr  signal_n3  \
0        0.994517   658.50   676.0        711        641  0.000944        239   
1        0.998988   495.00   508.0        535        482  0.001232        176   
2        1.001452  1098.25  1127.5       1187       1069  0.000558        393   
3        1.001762   545.50   560.0        591        531  0.001140        198   
4        0.999526  2542.25  2610.5       2747       2474  0.000243        918   
...           ...      ...     ...        ...        ...       ...        ...   
8133     1.004902   649.25   666.5        703        632  0.000943        232   
8134     1.001066   380.00   390.0        411        370  0.001650        139   
8135     0.999374   554.50   569.0        599        540  0.001100        197   
8136     1.000264   539.25   553.5        583        525  0.001132        192   
8137     0.999537  2666.75  2738.5       2883       2595  0.000232        963   

      Logdist_LNCacguD  Logdist_PCTacguD  Logdist_acguD         MFE   Up_Freq  
0            -1.151985         -1.154264       0.998026 -240.699997  0.129213  
1            -1.108212         -1.101415       1.006171 -195.500000  0.099065  
2            -1.242530         -1.243256       0.999417 -403.600006  0.112890  
3            -1.116135         -1.117372       0.998893 -214.899994  0.106780  
4            -1.536138         -1.528239       1.005169 -850.099976  0.109898  
...                ...               ...            ...         ...       ...  
8133         -1.749523         -1.791755       0.976430 -174.100006  0.128205  
8134         -1.990256         -2.041748       0.974781  -95.699997  0.126521  
8135         -1.087554         -1.091028       0.996816 -163.699997  0.120200  
8136         -1.106690         -1.099381       1.006649 -179.699997  0.120069  
8137         -1.087352         -1.089796       0.997758 -801.700012  0.119667  

[8138 rows x 17 columns]

In [79]:
import random
randnum=[random.random() for randnum in range(8138) ]

In [80]:
r1=dfnew['Logdist_LNCORF']
r2=dfnew['Logdist_PCTORF']

In [83]:
r1new=r1-randnum
r2new=r2-randnum

In [85]:
r3new=[]
for i in range(0,len(r1new)):
    r3new.append(r1new[i]/r2new[i])
    

In [86]:
dfnew['Logdist_LNCacguACGU']=r1new
dfnew['Logdist_PCTacguACGU']=r2new
dfnew['Logdist_acguACGU']=r3new

In [87]:
dfnew

Unnamed: 0  orf_length  orf_coverage  Logdist_LNCORF  Logdist_PCTORF  \
0              0         228      0.320225       -1.047841       -1.053617   
1              1         111      0.207477       -1.019344       -1.020377   
2              2         258      0.217355       -1.061407       -1.059868   
3              3         225      0.381356       -1.052068       -1.050217   
4              4         240      0.087336       -1.057371       -1.057873   
...          ...         ...           ...             ...             ...   
8133        8133         618      0.880342       -1.174580       -1.168850   
8134        8134          66      0.160584       -1.008640       -1.007566   
8135        8135          36      0.060100       -1.002576       -1.003204   
8136        8136         291      0.499142       -1.072277       -1.071994   
8137        8137        1779      0.617066       -1.562632       -1.563355   

      Logdist_ORF       Q1      Q2  max_value  min_value  ...  signal_n3  \
0        0.994517   658.50   676.0        711        641  ...        239   
1        0.998988   495.00   508.0        535        482  ...        176   
2        1.001452  1098.25  1127.5       1187       1069  ...        393   
3        1.001762   545.50   560.0        591        531  ...        198   
4        0.999526  2542.25  2610.5       2747       2474  ...        918   
...           ...      ...     ...        ...        ...  ...        ...   
8133     1.004902   649.25   666.5        703        632  ...        232   
8134     1.001066   380.00   390.0        411        370  ...        139   
8135     0.999374   554.50   569.0        599        540  ...        197   
8136     1.000264   539.25   553.5        583        525  ...        192   
8137     0.999537  2666.75  2738.5       2883       2595  ...        963   

      Logdist_LNCacguD  Logdist_PCTacguD  Logdist_acguD         MFE   Up_Freq  \
0            -1.151985         -1.154264       0.998026 -240.699997  0.129213   
1            -1.108212         -1.101415       1.006171 -195.500000  0.099065   
2            -1.242530         -1.243256       0.999417 -403.600006  0.112890   
3            -1.116135         -1.117372       0.998893 -214.899994  0.106780   
4            -1.536138         -1.528239       1.005169 -850.099976  0.109898   
...                ...               ...            ...         ...       ...   
8133         -1.749523         -1.791755       0.976430 -174.100006  0.128205   
8134         -1.990256         -2.041748       0.974781  -95.699997  0.126521   
8135         -1.087554         -1.091028       0.996816 -163.699997  0.120200   
8136         -1.106690         -1.099381       1.006649 -179.699997  0.120069   
8137         -1.087352         -1.089796       0.997758 -801.700012  0.119667   

      label  Logdist_LNCacguACGU  Logdist_PCTacguACGU  Logdist_acguACGU  
0         1            -1.599074            -1.604851          0.996401  
1         1            -1.456033            -1.457066          0.999291  
2         1            -1.930269            -1.928730          1.000798  
3         1            -1.325419            -1.323568          1.001398  
4         1            -1.419474            -1.419976          0.999647  
...     ...                  ...                  ...               ...  
8133      0            -1.284634            -1.278904          1.004480  
8134      0            -1.370190            -1.369116          1.000784  
8135      0            -1.801393            -1.802021          0.999651  
8136      0            -1.620762            -1.620478          1.000175  
8137      0            -2.422355            -2.423078          0.999702  

[8138 rows x 21 columns]

In [89]:
arr1=[]
for i in range(0,4056):
    arr1.append(1)
arr2=[]
for i in range(0,4082):
    arr2.append(0)
arr=arr1+arr2 

In [90]:
len(df)

8138

In [91]:
dfnew['label']=arr

In [92]:
df1=dfnew.drop(df.columns[0], axis=1) 

In [97]:
df1

orf_length  orf_coverage  Logdist_LNCORF  Logdist_PCTORF  Logdist_ORF  \
0            228      0.320225       -1.047841       -1.053617     0.994517   
1            111      0.207477       -1.019344       -1.020377     0.998988   
2            258      0.217355       -1.061407       -1.059868     1.001452   
3            225      0.381356       -1.052068       -1.050217     1.001762   
4            240      0.087336       -1.057371       -1.057873     0.999526   
...          ...           ...             ...             ...          ...   
8133         618      0.880342       -1.174580       -1.168850     1.004902   
8134          66      0.160584       -1.008640       -1.007566     1.001066   
8135          36      0.060100       -1.002576       -1.003204     0.999374   
8136         291      0.499142       -1.072277       -1.071994     1.000264   
8137        1779      0.617066       -1.562632       -1.563355     0.999537   

           Q1      Q2  max_value  min_value       snr  signal_n3  \
0      658.50   676.0        711        641  0.000944        239   
1      495.00   508.0        535        482  0.001232        176   
2     1098.25  1127.5       1187       1069  0.000558        393   
3      545.50   560.0        591        531  0.001140        198   
4     2542.25  2610.5       2747       2474  0.000243        918   
...       ...     ...        ...        ...       ...        ...   
8133   649.25   666.5        703        632  0.000943        232   
8134   380.00   390.0        411        370  0.001650        139   
8135   554.50   569.0        599        540  0.001100        197   
8136   539.25   553.5        583        525  0.001132        192   
8137  2666.75  2738.5       2883       2595  0.000232        963   

      Logdist_LNCacguD  Logdist_PCTacguD  Logdist_acguD         MFE   Up_Freq  \
0            -1.151985         -1.154264       0.998026 -240.699997  0.129213   
1            -1.108212         -1.101415       1.006171 -195.500000  0.099065   
2            -1.242530         -1.243256       0.999417 -403.600006  0.112890   
3            -1.116135         -1.117372       0.998893 -214.899994  0.106780   
4            -1.536138         -1.528239       1.005169 -850.099976  0.109898   
...                ...               ...            ...         ...       ...   
8133         -1.749523         -1.791755       0.976430 -174.100006  0.128205   
8134         -1.990256         -2.041748       0.974781  -95.699997  0.126521   
8135         -1.087554         -1.091028       0.996816 -163.699997  0.120200   
8136         -1.106690         -1.099381       1.006649 -179.699997  0.120069   
8137         -1.087352         -1.089796       0.997758 -801.700012  0.119667   

      label  Logdist_LNCacguACGU  Logdist_PCTacguACGU  Logdist_acguACGU  
0         1            -1.599074            -1.604851          0.996401  
1         1            -1.456033            -1.457066          0.999291  
2         1            -1.930269            -1.928730          1.000798  
3         1            -1.325419            -1.323568          1.001398  
4         1            -1.419474            -1.419976          0.999647  
...     ...                  ...                  ...               ...  
8133      0            -1.284634            -1.278904          1.004480  
8134      0            -1.370190            -1.369116          1.000784  
8135      0            -1.801393            -1.802021          0.999651  
8136      0            -1.620762            -1.620478          1.000175  
8137      0            -2.422355            -2.423078          0.999702  

[8138 rows x 20 columns]

In [98]:
df2=df1.dropna()
df2

orf_length  orf_coverage  Logdist_LNCORF  Logdist_PCTORF  Logdist_ORF  \
0            228      0.320225       -1.047841       -1.053617     0.994517   
1            111      0.207477       -1.019344       -1.020377     0.998988   
2            258      0.217355       -1.061407       -1.059868     1.001452   
3            225      0.381356       -1.052068       -1.050217     1.001762   
4            240      0.087336       -1.057371       -1.057873     0.999526   
...          ...           ...             ...             ...          ...   
8133         618      0.880342       -1.174580       -1.168850     1.004902   
8134          66      0.160584       -1.008640       -1.007566     1.001066   
8135          36      0.060100       -1.002576       -1.003204     0.999374   
8136         291      0.499142       -1.072277       -1.071994     1.000264   
8137        1779      0.617066       -1.562632       -1.563355     0.999537   

           Q1      Q2  max_value  min_value       snr  signal_n3  \
0      658.50   676.0        711        641  0.000944        239   
1      495.00   508.0        535        482  0.001232        176   
2     1098.25  1127.5       1187       1069  0.000558        393   
3      545.50   560.0        591        531  0.001140        198   
4     2542.25  2610.5       2747       2474  0.000243        918   
...       ...     ...        ...        ...       ...        ...   
8133   649.25   666.5        703        632  0.000943        232   
8134   380.00   390.0        411        370  0.001650        139   
8135   554.50   569.0        599        540  0.001100        197   
8136   539.25   553.5        583        525  0.001132        192   
8137  2666.75  2738.5       2883       2595  0.000232        963   

      Logdist_LNCacguD  Logdist_PCTacguD  Logdist_acguD         MFE   Up_Freq  \
0            -1.151985         -1.154264       0.998026 -240.699997  0.129213   
1            -1.108212         -1.101415       1.006171 -195.500000  0.099065   
2            -1.242530         -1.243256       0.999417 -403.600006  0.112890   
3            -1.116135         -1.117372       0.998893 -214.899994  0.106780   
4            -1.536138         -1.528239       1.005169 -850.099976  0.109898   
...                ...               ...            ...         ...       ...   
8133         -1.749523         -1.791755       0.976430 -174.100006  0.128205   
8134         -1.990256         -2.041748       0.974781  -95.699997  0.126521   
8135         -1.087554         -1.091028       0.996816 -163.699997  0.120200   
8136         -1.106690         -1.099381       1.006649 -179.699997  0.120069   
8137         -1.087352         -1.089796       0.997758 -801.700012  0.119667   

      label  Logdist_LNCacguACGU  Logdist_PCTacguACGU  Logdist_acguACGU  
0         1            -1.599074            -1.604851          0.996401  
1         1            -1.456033            -1.457066          0.999291  
2         1            -1.930269            -1.928730          1.000798  
3         1            -1.325419            -1.323568          1.001398  
4         1            -1.419474            -1.419976          0.999647  
...     ...                  ...                  ...               ...  
8133      0            -1.284634            -1.278904          1.004480  
8134      0            -1.370190            -1.369116          1.000784  
8135      0            -1.801393            -1.802021          0.999651  
8136      0            -1.620762            -1.620478          1.000175  
8137      0            -2.422355            -2.423078          0.999702  

[8127 rows x 20 columns]

In [100]:
import csv
df2.to_csv('MasterFeatureList.csv')

In [101]:
df3=df2.sample(frac=1)

In [107]:
df3.to_csv('MixedFeatureList.csv')

In [16]:
import pandas as pd
flist=pd.read_csv('MixedFeatureList.csv')
  

In [21]:
flist

Unnamed: 0  orf_length  orf_coverage  Logdist_LNCORF  Logdist_PCTORF  \
0           2692         291      0.315618       -1.074528       -1.072147   
1           7260        1599      0.634272       -1.479128       -1.494737   
2            795         327      0.106341       -1.088257       -1.086084   
3           5411         504      0.612394       -1.139230       -1.141939   
4           5407        1314      0.252887       -1.388258       -1.408681   
...          ...         ...           ...             ...             ...   
8122        2497         138      0.182058       -1.026068       -1.027083   
8123        3627         204      0.134299       -1.044385       -1.042806   
8124        6433         111      0.135863       -1.019802       -1.017351   
8125        6988         171      0.308664       -1.035140       -1.037052   
8126        1610         102      0.207317       -1.016040       -1.015056   

      Logdist_ORF       Q1      Q2  max_value  min_value  ...  signal_n3  \
0        1.002221   852.75   875.5        923        830  ...        305   
1        0.989557  2331.75  2394.5       2522       2269  ...        842   
2        1.002001  2844.50  2921.0       3075       2768  ...       1027   
3        0.997628   761.25   781.5        823        741  ...        272   
4        0.985502  4806.50  4936.0       5195       4677  ...       1734   
...           ...      ...     ...        ...        ...  ...        ...   
8122     0.999012   701.50   720.0        759        683  ...        254   
8123     1.001514  1405.50  1443.0       1519       1368  ...        504   
8124     1.002409   756.00   776.0        818        736  ...        274   
8125     0.998156   512.50   526.0        555        499  ...        186   
8126     1.000969   455.00   467.0        491        443  ...        166   

      Logdist_LNCacguD  Logdist_PCTacguD  Logdist_acguD          MFE  \
0            -1.320446         -1.318814       1.001237  -268.799988   
1            -1.101944         -1.098075       1.003523  -958.599976   
2            -1.292575         -1.287622       1.003847 -1121.800049   
3            -1.115900         -1.114686       1.001089  -279.600006   
4            -1.242065         -1.240898       1.000940 -2095.500000   
...                ...               ...            ...          ...   
8122         -1.242530         -1.243256       0.999417  -248.600006   
8123         -1.050586         -1.051038       0.999570  -331.299988   
8124         -1.156612         -1.154173       1.002113  -262.100006   
8125         -1.218530         -1.215549       1.002452  -171.699997   
8126         -1.412127         -1.426553       0.989888  -120.400002   

       Up_Freq  label  Logdist_LNCacguACGU  Logdist_PCTacguACGU  \
0     0.112798      1            -1.232061            -1.229680   
1     0.127727      0            -1.896056            -1.911666   
2     0.115772      1            -1.709728            -1.707555   
3     0.121507      0            -1.478622            -1.481331   
4     0.116821      0            -1.821159            -1.841582   
...        ...    ...                  ...                  ...   
8122  0.113456      1            -1.547067            -1.548082   
8123  0.115866      1            -1.516436            -1.514857   
8124  0.119951      0            -1.707505            -1.705054   
8125  0.135379      0            -1.693045            -1.694957   
8126  0.107724      1            -2.007286            -2.006302   

      Logdist_acguACGU  
0             1.001936  
1             0.991835  
2             1.001273  
3             0.998171  
4             0.988910  
...                ...  
8122          0.999344  
8123          1.001042  
8124          1.001438  
8125          0.998872  
8126          1.000490  

[8127 rows x 21 columns]

In [22]:
df4=df3.iloc[:,[5,6,7,8,9,10]]
df4

Logdist_ORF       Q1      Q2  max_value  min_value       snr
0        1.002221   852.75   875.5        923        830  0.000718
1        0.989557  2331.75  2394.5       2522       2269  0.000265
2        1.002001  2844.50  2921.0       3075       2768  0.000217
3        0.997628   761.25   781.5        823        741  0.000804
4        0.985502  4806.50  4936.0       5195       4677  0.000128
...           ...      ...     ...        ...        ...       ...
8122     0.999012   701.50   720.0        759        683  0.000885
8123     1.001514  1405.50  1443.0       1519       1368  0.000437
8124     1.002409   756.00   776.0        818        736  0.000822
8125     0.998156   512.50   526.0        555        499  0.001214
8126     1.000969   455.00   467.0        491        443  0.001374

[8127 rows x 6 columns]

In [39]:
df5=df3.drop('label',axis=1)
df5
target=df3['label']
target

0       1
1       0
2       1
3       0
4       0
       ..
8122    1
8123    1
8124    0
8125    0
8126    1
Name: label, Length: 8127, dtype: int64

In [44]:
df5d=df5.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]]
df5d

orf_length  orf_coverage  Logdist_LNCORF  Logdist_PCTORF  Logdist_ORF  \
0            291      0.315618       -1.074528       -1.072147     1.002221   
1           1599      0.634272       -1.479128       -1.494737     0.989557   
2            327      0.106341       -1.088257       -1.086084     1.002001   
3            504      0.612394       -1.139230       -1.141939     0.997628   
4           1314      0.252887       -1.388258       -1.408681     0.985502   
...          ...           ...             ...             ...          ...   
8122         138      0.182058       -1.026068       -1.027083     0.999012   
8123         204      0.134299       -1.044385       -1.042806     1.001514   
8124         111      0.135863       -1.019802       -1.017351     1.002409   
8125         171      0.308664       -1.035140       -1.037052     0.998156   
8126         102      0.207317       -1.016040       -1.015056     1.000969   

           Q1      Q2  max_value  min_value       snr  signal_n3  \
0      852.75   875.5        923        830  0.000718        305   
1     2331.75  2394.5       2522       2269  0.000265        842   
2     2844.50  2921.0       3075       2768  0.000217       1027   
3      761.25   781.5        823        741  0.000804        272   
4     4806.50  4936.0       5195       4677  0.000128       1734   
...       ...     ...        ...        ...       ...        ...   
8122   701.50   720.0        759        683  0.000885        254   
8123  1405.50  1443.0       1519       1368  0.000437        504   
8124   756.00   776.0        818        736  0.000822        274   
8125   512.50   526.0        555        499  0.001214        186   
8126   455.00   467.0        491        443  0.001374        166   

      Logdist_LNCacguD  Logdist_PCTacguD  Logdist_acguD          MFE  \
0            -1.320446         -1.318814       1.001237  -268.799988   
1            -1.101944         -1.098075       1.003523  -958.599976   
2            -1.292575         -1.287622       1.003847 -1121.800049   
3            -1.115900         -1.114686       1.001089  -279.600006   
4            -1.242065         -1.240898       1.000940 -2095.500000   
...                ...               ...            ...          ...   
8122         -1.242530         -1.243256       0.999417  -248.600006   
8123         -1.050586         -1.051038       0.999570  -331.299988   
8124         -1.156612         -1.154173       1.002113  -262.100006   
8125         -1.218530         -1.215549       1.002452  -171.699997   
8126         -1.412127         -1.426553       0.989888  -120.400002   

       Up_Freq  Logdist_LNCacguACGU  Logdist_PCTacguACGU  Logdist_acguACGU  
0     0.112798            -1.232061            -1.229680          1.001936  
1     0.127727            -1.896056            -1.911666          0.991835  
2     0.115772            -1.709728            -1.707555          1.001273  
3     0.121507            -1.478622            -1.481331          0.998171  
4     0.116821            -1.821159            -1.841582          0.988910  
...        ...                  ...                  ...               ...  
8122  0.113456            -1.547067            -1.548082          0.999344  
8123  0.115866            -1.516436            -1.514857          1.001042  
8124  0.119951            -1.707505            -1.705054          1.001438  
8125  0.135379            -1.693045            -1.694957          0.998872  
8126  0.107724            -2.007286            -2.006302          1.000490  

[8127 rows x 19 columns]

In [54]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
 
# To scale data
df6=scaler.fit_transform(df5d)

In [55]:
with open('transformed_data.pkl', 'wb') as f:
    pickle.dump(df6, f)

In [26]:
 with open('transformed_data.pkl', "rb") as fp:   # Unpickling
    b = pickle.load(fp)

In [34]:
df6

array([[-0.58625657, -0.36639497, -0.15571665, ...,  1.10898938,
         1.11471496,  0.66757555],
       [ 1.35843206,  0.80949129,  1.17088335, ..., -0.48058048,
        -0.50727846, -1.26935454],
       [-1.39384728, -0.33403113, -1.02696459, ..., -0.03452064,
        -0.02183357,  0.54035089],
       ...,
       [ 1.00636168, -0.52821418, -0.90406273, ..., -0.02919995,
        -0.01588621,  0.57198042],
       [ 1.24263624, -0.47427444, -0.18466695, ...,  0.00541696,
         0.0081282 ,  0.0800455 ],
       [-1.04688554, -0.53630514, -0.60658923, ..., -0.74685832,
        -0.73235516,  0.39036284]])

In [56]:
#model4- all features
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train4, X_test4, y_train4, y_test4 = train_test_split(df6, target, test_size=0.3,random_state=109) # 70% training and 30% test

In [57]:
import pickle
with open('trainingset_data.pkl', 'wb') as f:
    pickle.dump(X_train4, f)
with open('testset_data.pkl', 'wb') as f:
    pickle.dump(X_test4, f)
with open('trainingset_label.pkl', 'wb') as f:
    pickle.dump(y_train4, f)
with open('testset_label.pkl', 'wb') as f:
    pickle.dump(y_train4, f)

In [14]:
with open('trainingset_data.pkl', "rb") as fp:   # Unpickling
    X_train4 = pickle.load(fp)
with open('testset_data.pkl', "rb") as fp:   # Unpickling
    X_test4 = pickle.load(fp)
with open('trainingset_label.pkl', "rb") as fp:   # Unpickling
    y_train4 = pickle.load(fp)
with open('testset_label.pkl', "rb") as fp:   # Unpickling
    y_train4 = pickle.load(fp)

EOFError: Ran out of input

In [98]:
from sklearn import svm
import time
#Create a svm Classifier
clf4 = svm.SVC(kernel='linear') # Linear Kernel
s1=time.time()
#Train the model using the training sets
clf4.fit(X_train4, y_train4)

#Predict the response for test dataset
y_pred4 = clf4.predict(X_test4)

y_preddash4 = clf4.decision_function(X_test4)
e1=time.time()

In [59]:
X_train4

array([[-0.42303169, -0.6075576 ,  0.47150538, ...,  0.65324034,
         0.65579331,  0.26903657],
       [-0.55518405, -1.07342239,  0.612852  , ...,  0.54853702,
         0.55408229,  0.39690141],
       [-0.49045636, -0.60775715,  0.55862108, ...,  0.55058833,
         0.55823348,  0.51342404],
       ...,
       [-0.14254506, -0.00416746,  0.20690697, ...,  0.20174528,
         0.21721175,  0.77232717],
       [-0.18569685,  0.08557085,  0.1986414 , ..., -0.73189753,
        -0.73602955, -0.35405371],
       [-0.37718292, -1.08160142,  0.41421571, ...,  0.61626256,
         0.62199239,  0.43403183]])

In [99]:
t1=e1-s1
t1

1.0429093837738037

In [64]:
y_preddash4 = clf4.decision_function(X_test4)
y_preddash4

array([  0.12616667,  -2.78957383,   1.55088657, ..., -11.08750911,
         0.56936577,  -0.26589936])

In [65]:
X_train4[2]

array([-0.49045636, -0.60775715,  0.55862108,  0.56703623,  0.5388957 ,
       -0.59852773, -0.5985991 , -0.59886967, -0.59845239,  0.37165216,
       -0.60206184,  0.20060762,  0.20070704,  0.0219189 ,  0.61984575,
        1.43589377,  0.55058833,  0.55823348,  0.51342404])

In [66]:
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
acc4=metrics.accuracy_score(y_test4, y_pred4)
print("Accuracy:",metrics.accuracy_score(y_test4, y_pred4))

Accuracy: 0.8265682656826568


In [67]:
X_train4

array([[-0.42303169, -0.6075576 ,  0.47150538, ...,  0.65324034,
         0.65579331,  0.26903657],
       [-0.55518405, -1.07342239,  0.612852  , ...,  0.54853702,
         0.55408229,  0.39690141],
       [-0.49045636, -0.60775715,  0.55862108, ...,  0.55058833,
         0.55823348,  0.51342404],
       ...,
       [-0.14254506, -0.00416746,  0.20690697, ...,  0.20174528,
         0.21721175,  0.77232717],
       [-0.18569685,  0.08557085,  0.1986414 , ..., -0.73189753,
        -0.73602955, -0.35405371],
       [-0.37718292, -1.08160142,  0.41421571, ...,  0.61626256,
         0.62199239,  0.43403183]])

In [68]:
# Confusion matrix 
from sklearn import metrics
confusion4 = metrics.confusion_matrix(y_test4, y_pred4)
print(confusion4)

sens4=confusion4[0][0]/(confusion4[0][0]+confusion4[1][0])
spec4=confusion4[1][1]/(confusion4[1][1]+confusion4[0][1])
values4=[acc4,sens4,spec4]


[[ 829  366]
 [  57 1187]]


In [202]:
X_train4

array([[-0.42303169, -0.6075576 ,  0.47150538, ...,  0.65324034,
         0.65579331,  0.26903657],
       [-0.55518405, -1.07342239,  0.612852  , ...,  0.54853702,
         0.55408229,  0.39690141],
       [-0.49045636, -0.60775715,  0.55862108, ...,  0.55058833,
         0.55823348,  0.51342404],
       ...,
       [-0.14254506, -0.00416746,  0.20690697, ...,  0.20174528,
         0.21721175,  0.77232717],
       [-0.18569685,  0.08557085,  0.1986414 , ..., -0.73189753,
        -0.73602955, -0.35405371],
       [-0.37718292, -1.08160142,  0.41421571, ...,  0.61626256,
         0.62199239,  0.43403183]])

In [199]:
with open('model4.pkl','wb') as f:
    pickle.dump(clf4,f)

In [69]:
#model1- only eiip features
import numpy as np
X_train1=[]
for i in range(0,len(X_train4)):
    X_train1.append(np.delete(X_train4[i], [0,1,2,3,4,11,12,13,14,15,16,17,18]))

X_test1=[]
for i in range(0,len(X_test4)):
    X_test1.append(np.delete(X_test4[i], [0,1,2,3,4,11,12,13,14,15,16,17,18]))
# X_train1=np.delete(X_train4, [0,1,2,3,4])
# X_test1=np.delete(X_test4, [0,1,2,3,4])
y_train1=y_train4
y_test1=y_test4
#new_arr = np.delete(X_train4, [0,1,2,3,4])

In [106]:
len(y_test4)

2439

In [103]:
from sklearn import svm
s2=time.time()
#Create a svm Classifier
clf1 = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf1.fit(X_train1, y_train1)

#Predict the response for test dataset
y_pred1 = clf1.predict(X_test1)
y_preddash1 = clf1.decision_function(X_test1)
e2=time.time()

In [104]:
y_preddash1 = clf1.decision_function(X_test1)
y_preddash1

array([ 1.01237649, -0.00531833, -0.27132853, ..., -1.031956  ,
        0.92583615,  0.78565126])

In [105]:
t2=e2-s2
t2

1.3546860218048096

In [73]:
from sklearn import metrics
acc1=metrics.accuracy_score(y_test1, y_pred1)
# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test1, y_pred1))

Accuracy: 0.6482164821648216


In [74]:
# Confusion matrix 
from sklearn import metrics
confusion1 = metrics.confusion_matrix(y_test1, y_pred1)
print(confusion1)

sens1=confusion1[0][0]/(confusion1[0][0]+confusion1[1][0])
spec1=confusion1[1][1]/(confusion1[1][1]+confusion1[0][1])
values1=[acc1,sens1,spec1]

[[ 559  636]
 [ 222 1022]]


In [90]:
#model2-eiip+seq features(nolog distance)
# X_train2=X_train4.iloc[:,[0,1,5,6,7,8,9,10]]
# X_test2=X_test4.iloc[:,[0,1,5,6,7,8,9,10]]
X_train2=[]
for i in range(0,len(X_train4)):
    X_train2.append(np.delete(X_train4[i], [2,3,4,11,12,13,14,15,16,17,18]))

X_test2=[]
for i in range(0,len(X_test4)):
    X_test2.append(np.delete(X_test4[i], [2,3,4,11,12,13,14,15,16,17,18]))
y_train2=y_train4
y_test2=y_test4


In [91]:
#Create a svm Classifier
s3=time.time()
clf2 = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf2.fit(X_train2, y_train2)

#Predict the response for test dataset
y_pred2 = clf2.predict(X_test2)
y_preddash2 = clf2.decision_function(X_test2)
e3=time.time()

In [92]:
y_preddash2 = clf2.decision_function(X_test2)
y_preddash2

array([ 0.59776306, -1.28116674,  1.56623826, ..., -9.65880619,
        0.66650318,  0.20659378])

In [93]:
t3=e3-s3
t3

0.7012181282043457

In [79]:
from sklearn import metrics
acc2=metrics.accuracy_score(y_test2, y_pred2)
# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test2, y_pred2))

Accuracy: 0.8241082410824109


In [80]:
from sklearn import metrics
confusion2 = metrics.confusion_matrix(y_test2, y_pred2)
print(confusion2)

sens2=confusion2[0][0]/(confusion2[0][0]+confusion2[1][0])
spec2=confusion2[1][1]/(confusion2[1][1]+confusion2[0][1])
values2=[acc2,sens2,spec2]

[[ 807  388]
 [  41 1203]]


In [81]:
#model3- eiip+allseq features
# X_train3=X_train4.iloc[:,[0,1,2,3,4,5,6,7,8,9,10]]
# X_test3=X_test4.iloc[:,[0,1,2,3,4,5,6,7,8,9,10]]
X_train3=[]
for i in range(0,len(X_train4)):
    X_train3.append(np.delete(X_train4[i], [11,12,13,14,15,16,17,18]))

X_test3=[]
for i in range(0,len(X_test4)):
    X_test3.append(np.delete(X_test4[i], [11,12,13,14,15,16,17,18]))

y_train3=y_train4
y_test3=y_test4


In [85]:
#Create a svm Classifier
s4=time.time()
clf3 = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf3.fit(X_train3, y_train3)

#Predict the response for test dataset
y_pred3 = clf3.predict(X_test3)
y_preddash3 = clf3.decision_function(X_test3)
e4=time.time()

In [86]:
y_preddash3 = clf3.decision_function(X_test3)
y_preddash3

array([  0.50823836,  -3.07452701,   1.67404102, ..., -10.79898085,
         0.41297228,  -0.15178999])

In [87]:
t4=e4-s4
t4

0.8285558223724365

In [88]:
from sklearn import metrics
acc3=metrics.accuracy_score(y_test3, y_pred3)
# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test3, y_pred3))

Accuracy: 0.8228782287822878


In [89]:
from sklearn import metrics
confusion3 = metrics.confusion_matrix(y_test3, y_pred3)
print(confusion3)

sens3=confusion3[0][0]/(confusion3[0][0]+confusion3[1][0])
spec3=confusion3[1][1]/(confusion3[1][1]+confusion3[0][1])
values3=[acc3,sens3,spec3]

[[ 823  372]
 [  60 1184]]


In [230]:
import pickle

# save
with open('model1.pkl','wb') as f:
    pickle.dump(clf1,f)

In [231]:
import pickle

# save
with open('model2.pkl','wb') as f:
    pickle.dump(clf2,f)

In [232]:
import pickle

# save
with open('model3.pkl','wb') as f:
    pickle.dump(clf3,f)

In [233]:
all_values=[values1,values2,values3,values4]
all_values

[[0.6478064780647806, 0.7148337595907929, 0.616173808086904],
 [0.8241082410824109, 0.9516509433962265, 0.7561282212445003],
 [0.8228782287822878, 0.9320498301245753, 0.7609254498714653],
 [0.8265682656826568, 0.9356659142212189, 0.7643271088216356]]

In [234]:
all_predvalues=[y_pred1,y_pred2,y_pred3,y_pred4]

In [235]:
all_predvalues

[array([1, 0, 0, ..., 0, 1, 1], dtype=int64),
 array([1, 0, 1, ..., 0, 1, 1], dtype=int64),
 array([1, 0, 1, ..., 0, 1, 0], dtype=int64),
 array([1, 0, 1, ..., 0, 1, 0], dtype=int64)]

In [238]:
all_preddashvalues=[y_preddash1,y_preddash2,y_preddash3,y_preddash4]

In [252]:
ypdash = pd.DataFrame(all_preddashvalues)
ypdash=ypdash.T
ypdash['label']=list(y_test4)


In [254]:
ypdash.to_csv('scoringnums.csv',index=False)

In [239]:
with open('ypreddashvalues.pkl','wb') as f:
    pickle.dump(all_preddashvalues,f)

In [236]:
with open('accvalues.pkl','wb') as f:
    pickle.dump(all_values,f)

In [237]:
with open('ypredvalues.pkl','wb') as f:
    pickle.dump(all_predvalues,f)

In [165]:
#tester model 5 without acguACGU
#model3- eiip+allseq features
X_train5=X_train4.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]
X_test5=X_test4.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]
y_train5=y_train4
y_test5=y_test4

In [166]:
#Create a svm Classifier
clf5 = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf5.fit(X_train5, y_train5)

#Predict the response for test dataset
y_pred5 = clf5.predict(X_test5)

In [167]:
from sklearn import metrics
acc5=metrics.accuracy_score(y_test5, y_pred5)
# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test5, y_pred5))

Accuracy: 0.8187781877818778


In [169]:
#calculating scores for each svm model
with open('model1.pkl', 'rb') as f:
    mod1 = pickle.load(f)

In [170]:
y_preddash1 = mod1.decision_function(X_test1)

In [171]:
y_preddash1

array([  27.86089607,  -64.48300716,  -81.05259194, ..., -134.8690046 ,
         15.76153354,   11.85238961])

In [175]:
X_train4

orf_length  orf_coverage  Logdist_LNCORF  Logdist_PCTORF  Logdist_ORF  \
674          228      0.207084       -1.054320       -1.054522     0.999808   
3790          81      0.095182       -1.011609       -1.010840     1.000760   
2945         153      0.207037       -1.027996       -1.026339     1.001615   
3550          96      0.228029       -1.015836       -1.015642     1.000191   
3808         288      0.089804       -1.070987       -1.070314     1.000629   
...          ...           ...             ...             ...          ...   
398          267      0.260488       -1.063118       -1.061768     1.001272   
2403         186      0.194561       -1.039970       -1.038832     1.001095   
5908         540      0.352021       -1.134274       -1.130285     1.003530   
85           492      0.373576       -1.136772       -1.143583     0.994045   
420          279      0.093218       -1.071631       -1.070599     1.000964   

           Q1      Q2  max_value  min_value       snr  signal_n3  \
674   1018.25  1045.5       1102        991  0.000603        365   
3790   787.00   808.0        851        766  0.000777        281   
2945   684.00   702.0        739        666  0.000895        244   
3550   389.25   399.5        422        379  0.001606        142   
3808  2966.75  3046.5       3207       2887  0.000208       1071   
...       ...     ...        ...        ...       ...        ...   
398    948.25   973.5       1026        923  0.000654        343   
2403   884.50   908.0        955        861  0.000692        316   
5908  1419.00  1457.0       1535       1381  0.000433        509   
85    1218.50  1251.0       1318       1186  0.000504        437   
420   2768.50  2843.0       2994       2694  0.000223        999   

      Logdist_LNCacguD  Logdist_PCTacguD  Logdist_acguD          MFE  \
674          -1.058521         -1.055351       1.003004  -361.600006   
3790         -1.280366         -1.278483       1.001473  -213.600006   
2945         -1.215401         -1.216367       0.999206  -215.800003   
3550         -1.567745         -1.552851       1.009591  -119.699997   
3808         -1.415853         -1.420287       0.996878 -1022.400024   
...                ...               ...            ...          ...   
398          -1.206377         -1.204398       1.001643  -328.799988   
2403         -1.689846         -1.704262       0.991542  -345.799988   
5908         -1.249704         -1.247186       1.002019  -491.100006   
85           -1.275712         -1.278076       0.998150  -433.200012   
420          -1.632219         -1.635798       0.997812 -1065.599976   

       Up_Freq  Logdist_LNCacguACGU  Logdist_PCTacguACGU  Logdist_acguACGU  
674   0.115350            -1.422436            -1.422639          0.999858  
3790  0.118684            -1.466173            -1.465405          1.000524  
2945  0.129905            -1.465316            -1.463659          1.001132  
3550  0.114014            -1.775633            -1.775439          1.000109  
3808  0.115061            -1.743335            -1.742662          1.000387  
...        ...                  ...                  ...               ...  
398   0.104390            -1.127670            -1.126319          1.001199  
2403  0.119247            -1.451283            -1.450145          1.000784  
5908  0.110169            -1.611035            -1.607046          1.002482  
85    0.118451            -2.001036            -2.007847          0.996608  
420   0.118610            -1.437883            -1.436851          1.000718  

[5688 rows x 19 columns]

In [112]:
dfh = pd.DataFrame({"val": list(y_pred4),'scores':list(y_preddash4)})
dfh

val     scores
0       1   0.126167
1       0  -2.789574
2       1   1.550887
3       0  -2.847339
4       0  -0.335257
...   ...        ...
2434    1   0.954255
2435    1   0.189827
2436    0 -11.087509
2437    1   0.569366
2438    0  -0.265899

[2439 rows x 2 columns]

In [113]:
tr=dfh[dfh['scores'] > 0.1]
tr

val    scores
0       1  0.126167
2       1  1.550887
5       1  1.553737
7       1  0.850166
9       1  1.376456
...   ...       ...
2431    1  0.405601
2433    1  0.772186
2434    1  0.954255
2435    1  0.189827
2437    1  0.569366

[1522 rows x 2 columns]